### ISSUE TITLE
Replace the logo by SVG file

### ISSUE THREAD

**Issue by colourfreak** [TokenScript/token-negotiator-gh-pages#1]
You can export to SVG from Zeplin:
<img width="888" alt="Screenshot 2022-03-18 at 07 00 25" src="https://user-images.githubusercontent.com/51817359/158946448-eb1590d8-904a-4b50-a93a-59863b4de4b7.png">

Zeplin
https://zpl.io/GEk6qjj

**Comment by nicktaras** [comment]
Complete.

[No problem Tomek, this is fixed](https://tokenscript.github.io/token-negotiator-gh-pages/#/)
