### ISSUE TITLE
Make all project images in the same size

### ISSUE THREAD

**Issue by colourfreak** [TokenScript/token-negotiator-gh-pages#3]
Currently, we have this "jump" when you are browsing projects. And whole CSS changes depending on the width of a project's image.

https://user-images.githubusercontent.com/51817359/158948581-790c6b7e-2e0c-4a72-8a86-46fdb60ec7b5.mov

**Comment by colourfreak** [comment]
in other words "Hotel Bogota (Active Negotiation)" is not in the same place as "Devcon Ticket Issuer (with url)"

**Comment by nicktaras** [comment]
Fixed this issue uploading high res images to the website.
